### ISSUE TITLE
Daha fazla ders notu gerekmekte

### ISSUE THREAD

**Issue by yedhrab** [yedhrab/IstanbulUniversity-CE#1]
Elinde **ders notu olan** kişilerin benimle [buradan](mailto::yedhrab@gmail.com?subject=IU-CE-DersNotlari%20%7C%20Github) iletişime geçebilir ya da projeye katkıda bulunabilir 🙏

**Comment by afozbek** [comment]
Ne gibi ders notlarınıza ihtiyacınız var Yunus Bey

**Comment by yedhrab** [comment]
Okumadığım dönemlerin notları bir hayli az:

- 1.sınıf dönemleri
- 4.sınıf dönemleri

Bunlara ek olarak, bu sürecin başlarında olduğum vakitlerin notları da düzensizdir

- 2.sınıf 1.dönem notları

Elinde olan faydalı linklerin ve kişisel ders notlarını paylaşırsan okulumuzda okuyanlar için bir hayli faydalı olacaktır.

**Comment by afozbek** [comment]
Elimden geldiğince katkı sağlamaya çalışacağım
