### ISSUE TITLE
Contributors.md dosyası oluşturulması

### ISSUE THREAD

**Issue by afozbek** [yedhrab/IstanbulUniversity-CE#14]
## Özellik Özeti 💡

Geliştiriciler için contributors.md dosyası oluşturulabilir.

## Neden bu özelliğe ihtiyacımız olsun?

Çünkü geliştirme yapmak isteyen yazılımcılar veya öğrenciler nasıl formatta geliştirilme yapılması gerektiğini öğrenebilir.

## Bunu nasıl uygulamayı tavsiye edersin?

Readme.md dosyasına bu link verilebilir. Gerekli dosya da ana dizinde oluşturulursa projeye bakan kişi direk olarak reponun ana dizininde bu dosyaya bakabilir

**Comment by yedhrab** [comment]
😳 Onu onu unutamam kötü olmuş. "💖 Katkıda Bulunma Rehberi" başlığı altında oluşturuldu, yardımın için teşekkürler 😊

**Comment by yedhrab** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Data Comminication notları eklenecek](https://trello.com/c/7REPcsGy/1-data-comminication-notlar%C4%B1-eklenecek)
